ckpt_name: "ResNet101_SUN_PS_C"
db_name: "SUN"
split: "PS"
gpu: "3"
model: "ResNet101"

test:
    batch_size: 32
    setting: "c"
    epoch: "all"
    imload_mode: "resize_crop"
    self_adaptions: 10
    save_predictions: True

train:
    batch_size: 64
    epochs: 20
    lr_decay: 20
    lr: 1e-05
    beta: 0.5
    log_inter: 64
    ckpt_inter: 1
    data_aug: "resize_random_crop"
    triplet_mode: "batch_hard"
