ckpt_name: "VGG19_SUN_PS_C"
db_name: "SUN"
split: "PS"
gpu: "3"
model: "VGG19"

test:
    batch_size: 32
    setting: "c"
    epoch: "all"
    imload_mode: "resize_crop"
    self_adaptions: 10
    save_predictions: True

train:
    batch_size: 24
    epochs: 15
    lr_decay: 10
    lr: 5e-05
    beta: 1.0
    log_inter: 24
    ckpt_inter: 1
    data_aug: "resize_random_crop+colorjitter"
    triplet_mode: "batch_hard"
