ckpt_name: "ResNet101_SUN_SS_C"
db_name: "SUN"
split: "SS"
gpu: "3"
model: "ResNet101"

test:
    batch_size: 32
    setting: "c"
    epoch: "all"
    imload_mode: "TenCrop"
    self_adaptions: 10
    save_predictions: True

train:
    batch_size: 64
    epochs: 25
    lr_decay: 30
    lr: 1e-05
    beta: 1.0
    log_inter: 64
    ckpt_inter: 1
    data_aug: "resize_random_crop"
    triplet_mode: "batch_hard"
